### ISSUE TITLE
parent - open up the map routes a bit more

### ISSUE THREAD

**Issue by FixingGen1** [FixingGen1/blueconfig#163]
- [x] pallet town to route 1 opened up #168 
- [x] route 2 digletts cave area #169 
- [x] route 3 / r4 route 4 - mt moon skippable #170 
- [x] cerulean city more open
- [x] route 6 to vermillion
- [x] vermillion gym no puzzle
- [x] celadon gym open
- [x] open saffron to get psychic earlier
- [x] rock tunnel is optional
- [x] route 12 / 13 / 14
- [x] sea route has a walkway
- [x] unknown dungeon
